# Copyright (C) 2013-2016 The CyanogenMod Project
# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/m7/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/htc/m7/proprietary/etc/firmware/BCM4335B0_002.001.006.0296.0297.hcd:system/etc/firmware/BCM4335B0_002.001.006.0296.0297.hcd \
    vendor/htc/m7/proprietary/etc/firmware/BCM4335B0_002.001.006.0296.0299.hcd:system/etc/firmware/BCM4335B0_002.001.006.0296.0299.hcd
PRODUCT_COPY_FILES += \
    vendor/htc/m7/proprietary/blobs/gsm/bin/efsks:$(TARGET_COPY_OUT_VENDOR)/blobs/gsm/bin/efsks \
    vendor/htc/m7/proprietary/blobs/gsm/bin/netmgrd:$(TARGET_COPY_OUT_VENDOR)/blobs/gsm/bin/netmgrd \
    vendor/htc/m7/proprietary/blobs/gsm/bin/qcks:$(TARGET_COPY_OUT_VENDOR)/blobs/gsm/bin/qcks \
    vendor/htc/m7/proprietary/blobs/gsm/bin/qmuxd:$(TARGET_COPY_OUT_VENDOR)/blobs/gsm/bin/qmuxd \
    vendor/htc/m7/proprietary/blobs/gsm/lib/libdiag.so:$(TARGET_COPY_OUT_VENDOR)/blobs/gsm/lib/libdiag.so \
    vendor/htc/m7/proprietary/blobs/gsm/lib/libdsi_netctrl.so:$(TARGET_COPY_OUT_VENDOR)/blobs/gsm/lib/libdsi_netctrl.so \
    vendor/htc/m7/proprietary/blobs/gsm/lib/libdsutils.so:$(TARGET_COPY_OUT_VENDOR)/blobs/gsm/lib/libdsutils.so \
    vendor/htc/m7/proprietary/blobs/gsm/lib/libidl.so:$(TARGET_COPY_OUT_VENDOR)/blobs/gsm/lib/libidl.so \
    vendor/htc/m7/proprietary/blobs/gsm/lib/libnetmgr.so:$(TARGET_COPY_OUT_VENDOR)/blobs/gsm/lib/libnetmgr.so \
    vendor/htc/m7/proprietary/blobs/gsm/lib/libqcci_legacy.so:$(TARGET_COPY_OUT_VENDOR)/blobs/gsm/lib/libqcci_legacy.so \
    vendor/htc/m7/proprietary/blobs/gsm/lib/libqdi.so:$(TARGET_COPY_OUT_VENDOR)/blobs/gsm/lib/libqdi.so \
    vendor/htc/m7/proprietary/blobs/gsm/lib/libqdp.so:$(TARGET_COPY_OUT_VENDOR)/blobs/gsm/lib/libqdp.so \
    vendor/htc/m7/proprietary/blobs/gsm/lib/libqmi.so:$(TARGET_COPY_OUT_VENDOR)/blobs/gsm/lib/libqmi.so \
    vendor/htc/m7/proprietary/blobs/gsm/lib/libqmi_cci.so:$(TARGET_COPY_OUT_VENDOR)/blobs/gsm/lib/libqmi_cci.so \
    vendor/htc/m7/proprietary/blobs/gsm/lib/libqmi_client_qmux.so:$(TARGET_COPY_OUT_VENDOR)/blobs/gsm/lib/libqmi_client_qmux.so \
    vendor/htc/m7/proprietary/blobs/gsm/lib/libqmi_common_so.so:$(TARGET_COPY_OUT_VENDOR)/blobs/gsm/lib/libqmi_common_so.so \
    vendor/htc/m7/proprietary/blobs/gsm/lib/libqmi_csi.so:$(TARGET_COPY_OUT_VENDOR)/blobs/gsm/lib/libqmi_csi.so \
    vendor/htc/m7/proprietary/blobs/gsm/lib/libqmi_encdec.so:$(TARGET_COPY_OUT_VENDOR)/blobs/gsm/lib/libqmi_encdec.so \
    vendor/htc/m7/proprietary/blobs/gsm/lib/libqmiservices.so:$(TARGET_COPY_OUT_VENDOR)/blobs/gsm/lib/libqmiservices.so \
    vendor/htc/m7/proprietary/blobs/gsm/lib/libril-qc-qmi-1.so:$(TARGET_COPY_OUT_VENDOR)/blobs/gsm/lib/libril-qc-qmi-1.so \
    vendor/htc/m7/proprietary/blobs/gsm/lib/libril-qcril-hook-oem.so:$(TARGET_COPY_OUT_VENDOR)/blobs/gsm/lib/libril-qcril-hook-oem.so \
    vendor/htc/m7/proprietary/blobs/vzw/bin/efsks:$(TARGET_COPY_OUT_VENDOR)/blobs/vzw/bin/efsks \
    vendor/htc/m7/proprietary/blobs/vzw/bin/netmgrd:$(TARGET_COPY_OUT_VENDOR)/blobs/vzw/bin/netmgrd \
    vendor/htc/m7/proprietary/blobs/vzw/bin/qcks:$(TARGET_COPY_OUT_VENDOR)/blobs/vzw/bin/qcks \
    vendor/htc/m7/proprietary/blobs/vzw/bin/qmuxd:$(TARGET_COPY_OUT_VENDOR)/blobs/vzw/bin/qmuxd \
    vendor/htc/m7/proprietary/blobs/vzw/lib/libdiag.so:$(TARGET_COPY_OUT_VENDOR)/blobs/vzw/lib/libdiag.so \
    vendor/htc/m7/proprietary/blobs/vzw/lib/libdsi_netctrl.so:$(TARGET_COPY_OUT_VENDOR)/blobs/vzw/lib/libdsi_netctrl.so \
    vendor/htc/m7/proprietary/blobs/vzw/lib/libdsutils.so:$(TARGET_COPY_OUT_VENDOR)/blobs/vzw/lib/libdsutils.so \
    vendor/htc/m7/proprietary/blobs/vzw/lib/libidl.so:$(TARGET_COPY_OUT_VENDOR)/blobs/vzw/lib/libidl.so \
    vendor/htc/m7/proprietary/blobs/vzw/lib/libnetmgr.so:$(TARGET_COPY_OUT_VENDOR)/blobs/vzw/lib/libnetmgr.so \
    vendor/htc/m7/proprietary/blobs/vzw/lib/libqcci_legacy.so:$(TARGET_COPY_OUT_VENDOR)/blobs/vzw/lib/libqcci_legacy.so \
    vendor/htc/m7/proprietary/blobs/vzw/lib/libqdi.so:$(TARGET_COPY_OUT_VENDOR)/blobs/vzw/lib/libqdi.so \
    vendor/htc/m7/proprietary/blobs/vzw/lib/libqdp.so:$(TARGET_COPY_OUT_VENDOR)/blobs/vzw/lib/libqdp.so \
    vendor/htc/m7/proprietary/blobs/vzw/lib/libqmi.so:$(TARGET_COPY_OUT_VENDOR)/blobs/vzw/lib/libqmi.so \
    vendor/htc/m7/proprietary/blobs/vzw/lib/libqmi_cci.so:$(TARGET_COPY_OUT_VENDOR)/blobs/vzw/lib/libqmi_cci.so \
    vendor/htc/m7/proprietary/blobs/vzw/lib/libqmi_client_qmux.so:$(TARGET_COPY_OUT_VENDOR)/blobs/vzw/lib/libqmi_client_qmux.so \
    vendor/htc/m7/proprietary/blobs/vzw/lib/libqmi_common_so.so:$(TARGET_COPY_OUT_VENDOR)/blobs/vzw/lib/libqmi_common_so.so \
    vendor/htc/m7/proprietary/blobs/vzw/lib/libqmi_csi.so:$(TARGET_COPY_OUT_VENDOR)/blobs/vzw/lib/libqmi_csi.so \
    vendor/htc/m7/proprietary/blobs/vzw/lib/libqmi_encdec.so:$(TARGET_COPY_OUT_VENDOR)/blobs/vzw/lib/libqmi_encdec.so \
    vendor/htc/m7/proprietary/blobs/vzw/lib/libqmiservices.so:$(TARGET_COPY_OUT_VENDOR)/blobs/vzw/lib/libqmiservices.so \
    vendor/htc/m7/proprietary/blobs/vzw/lib/libril-qc-qmi-1.so:$(TARGET_COPY_OUT_VENDOR)/blobs/vzw/lib/libril-qc-qmi-1.so \
    vendor/htc/m7/proprietary/blobs/vzw/lib/libril-qcril-hook-oem.so:$(TARGET_COPY_OUT_VENDOR)/blobs/vzw/lib/libril-qcril-hook-oem.so \
    vendor/htc/m7/proprietary/blobs/spr/bin/efsks:$(TARGET_COPY_OUT_VENDOR)/blobs/spr/bin/efsks \
    vendor/htc/m7/proprietary/blobs/spr/bin/netmgrd:$(TARGET_COPY_OUT_VENDOR)/blobs/spr/bin/netmgrd \
    vendor/htc/m7/proprietary/blobs/spr/bin/qcks:$(TARGET_COPY_OUT_VENDOR)/blobs/spr/bin/qcks \
    vendor/htc/m7/proprietary/blobs/spr/bin/qmuxd:$(TARGET_COPY_OUT_VENDOR)/blobs/spr/bin/qmuxd \
    vendor/htc/m7/proprietary/blobs/spr/lib/libdiag.so:$(TARGET_COPY_OUT_VENDOR)/blobs/spr/lib/libdiag.so \
    vendor/htc/m7/proprietary/blobs/spr/lib/libdsi_netctrl.so:$(TARGET_COPY_OUT_VENDOR)/blobs/spr/lib/libdsi_netctrl.so \
    vendor/htc/m7/proprietary/blobs/spr/lib/libdsutils.so:$(TARGET_COPY_OUT_VENDOR)/blobs/spr/lib/libdsutils.so \
    vendor/htc/m7/proprietary/blobs/spr/lib/libidl.so:$(TARGET_COPY_OUT_VENDOR)/blobs/spr/lib/libidl.so \
    vendor/htc/m7/proprietary/blobs/spr/lib/libnetmgr.so:$(TARGET_COPY_OUT_VENDOR)/blobs/spr/lib/libnetmgr.so \
    vendor/htc/m7/proprietary/blobs/spr/lib/libqcci_legacy.so:$(TARGET_COPY_OUT_VENDOR)/blobs/spr/lib/libqcci_legacy.so \
    vendor/htc/m7/proprietary/blobs/spr/lib/libqdi.so:$(TARGET_COPY_OUT_VENDOR)/blobs/spr/lib/libqdi.so \
    vendor/htc/m7/proprietary/blobs/spr/lib/libqdp.so:$(TARGET_COPY_OUT_VENDOR)/blobs/spr/lib/libqdp.so \
    vendor/htc/m7/proprietary/blobs/spr/lib/libqmi.so:$(TARGET_COPY_OUT_VENDOR)/blobs/spr/lib/libqmi.so \
    vendor/htc/m7/proprietary/blobs/spr/lib/libqmi_cci.so:$(TARGET_COPY_OUT_VENDOR)/blobs/spr/lib/libqmi_cci.so \
    vendor/htc/m7/proprietary/blobs/spr/lib/libqmi_client_qmux.so:$(TARGET_COPY_OUT_VENDOR)/blobs/spr/lib/libqmi_client_qmux.so \
    vendor/htc/m7/proprietary/blobs/spr/lib/libqmi_common_so.so:$(TARGET_COPY_OUT_VENDOR)/blobs/spr/lib/libqmi_common_so.so \
    vendor/htc/m7/proprietary/blobs/spr/lib/libqmi_csi.so:$(TARGET_COPY_OUT_VENDOR)/blobs/spr/lib/libqmi_csi.so \
    vendor/htc/m7/proprietary/blobs/spr/lib/libqmi_encdec.so:$(TARGET_COPY_OUT_VENDOR)/blobs/spr/lib/libqmi_encdec.so \
    vendor/htc/m7/proprietary/blobs/spr/lib/libqmiservices.so:$(TARGET_COPY_OUT_VENDOR)/blobs/spr/lib/libqmiservices.so \
    vendor/htc/m7/proprietary/blobs/spr/lib/libril-qc-qmi-1.so:$(TARGET_COPY_OUT_VENDOR)/blobs/spr/lib/libril-qc-qmi-1.so \
    vendor/htc/m7/proprietary/blobs/spr/lib/libril-qcril-hook-oem.so:$(TARGET_COPY_OUT_VENDOR)/blobs/spr/lib/libril-qcril-hook-oem.so